### PR TITLE
Use octokit throttling plugin to avoid rate limiting error when committing on github

### PR DESCRIPTION
**Pull request by dengl11**

### CODE REVIEW

**Comment by hexecute** [comment]
Did you accidentally commit the node_modules/ folder? If so, you might have to do some fancy Git handling to remove the node_modules/ files from the Git history (otherwise, the size of the repo balloons).

**Comment by dengl11** [comment]
I agree.

Ideally we can just do `npm install` in the yml file as part of the action. But that might slow down the building process. I was wondering if that if Josh's original motivation for keeping the `node_modules`; so I sticked to keeping them.

Josh, WDYT?

**Comment by joshcai** [comment]
Thanks @dengl11 and @hexecute for looking at this! I normally don't commit node_modules, but for JavaScript based GitHub Actions, it seems like it's necessary (possibly to save time on the action runners):

https://docs.github.com/en/actions/creating-actions/creating-a-javascript-action#commit-tag-and-push-your-action-to-github

For the pull request, as @dengl11 mentioned in https://github.com/joshcai/leetcode-sync/issues/1, I think the best might be to let the users re-run manually. We could also add an option that allows the user to commit everything on the same day (when the action runs instead of when the solution was submitted), which would reduce the number of GitHub API requests. 

It's not super clear to me what the rate limiting policy actually is - earlier I thought it was 5000 requests for authenticated users: https://developer.github.com/apps/building-github-apps/understanding-rate-limits-for-github-apps/, so I'm surprised we're hitting it. We could debug by looking at the rate limit API: https://docs.github.com/en/rest/reference/rate-limit, but if it resets every hour, then I don't think it makes sense to keep the runner waiting for so long just to do the retry after.

**Comment by joshcai** [comment]
There's now a new way to bundle the dependencies into a single file (ncc) so that we don't need to commit node_modules anymore: https://docs.github.com/en/actions/creating-actions/creating-a-javascript-action#commit-tag-and-push-your-action-to-github (I'm in the process of migrating to this now) 

Also, closing this pull request since it is not needed anymore as discussed earlier. Thanks all!

**Pull request closed without merging**
